build:
	go build -o main main.go pointerAnalysis.go raceCollection.go sliceTools.go ssaInstructions.go staticAnalysis.go
runCockroach:
	./main GoBench/Cockroach/27659/main.go
	./main GoBench/Cockroach/35501/main.go
runEtcd:
	./main GoBench/Etcd/4876/main.go
	./main GoBench/Etcd/8149/main.go
	./main GoBench/Etcd/9446/main.go
runGrpc:
	./main GoBench/Grpc/1748/main.go
	./main GoBench/Grpc/1862/main.go
	./main GoBench/Grpc/3090/main.go
runIstio:
	./main GoBench/Istio/8144/main.go
	./main GoBench/Istio/8214/main.go
	./main GoBench/Istio/8967/main.go
	./main GoBench/Istio/16742/main.go
runServing:
	./main GoBench/Serving/3148/main.go
runGoBench:
	./main GoBench/Cockroach/27659/main.go
	./main GoBench/Cockroach/35501/main.go
	./main GoBench/Etcd/4876/main.go
	./main GoBench/Etcd/8149/main.go
	./main GoBench/Etcd/9446/main.go
	./main GoBench/Grpc/1748/main.go
	./main GoBench/Grpc/1862/main.go
	./main GoBench/Grpc/3090/main.go
	./main GoBench/Istio/8144/main.go
	./main GoBench/Istio/8214/main.go
	./main GoBench/Istio/8967/main.go
	./main GoBench/Istio/16742/main.go
	./main GoBench/Kubernetes/79631/main.go
	./main GoBench/Kubernetes/80284/main.go
	./main GoBench/Kubernetes/81091/main.go
	./main GoBench/Kubernetes/81148/main.go
	./main GoBench/Kubernetes/88331/main.go
	./main GoBench/Serving/3148/main.go
runGodel2Race:
	./main godel2/ch-as-lock-race/main.go
	./main godel2/deposit-race/main.go
	./main godel2/prod-cons-race/main.go
	./main godel2/simple-race/main.go
	./main godel2/dine3-chan-race/main.go
	./main godel2/dine5-chan-race/main.go
runGodel2NoRace:
	./main godel2/ch-as-lock-fix/main.go
	./main godel2/deposit-fix/main.go
	./main godel2/prod-cons-fix/main.go
	./main godel2/simple-race-fix/main.go
	./main godel2/no-race/main.go
	./main godel2/dine3-chan-fix/main.go
	./main godel2/dine5-chan-fix/main.go
run:
	./main GoBench/Cockroach/27659/main.go
	./main GoBench/Cockroach/35501/main.go
	./main GoBench/Etcd/4876/main.go
	./main GoBench/Etcd/8149/main.go
	./main GoBench/Etcd/9446/main.go
	./main GoBench/Grpc/1748/main.go
	./main GoBench/Grpc/1862/main.go
	./main GoBench/Grpc/3090/main.go
	./main GoBench/Istio/8144/main.go
	./main GoBench/Istio/8214/main.go
	./main GoBench/Istio/8967/main.go
	./main GoBench/Istio/16742/main.go
	./main GoBench/Kubernetes/79631/main.go
	./main GoBench/Kubernetes/80284/main.go
	./main GoBench/Kubernetes/81091/main.go
	./main GoBench/Kubernetes/81148/main.go
	./main GoBench/Kubernetes/88331/main.go
	./main GoBench/Serving/3148/main.go
	./main godel2/ch-as-lock-race/main.go
	./main godel2/deposit-race/main.go
	./main godel2/prod-cons-race/main.go
	./main godel2/simple-race/main.go
	./main godel2/dine3-chan-race/main.go
	./main godel2/dine5-chan-race/main.go