build:
	go build -o main main.go pointerAnalysis.go raceCollection.go sliceTools.go ssaInstructions.go staticAnalysis.go
runKubed:
	go run ./main test-kubed/main.go
runNakama:
	go run ./main test-nakama/main.go
runHugo:
	go run ./main test-hugo/hugo-master/main.go
runTalisman:
	go run ./main test-talisman/talisman.go
runJsonnet:
	go run ./main test-jsonnet/cmd/jsonnet/cmd.go
runKsonnet:
	go run ./main test-ksonnet/cmd/ks/main.go
runGitea:
	go run ./main test-gitea/main.go
runFaas:
	go run ./main test-faas/gateway/main.go
runKit:
	go run ./main test-kit/cmd/kitgen/main.go
runMicro:
	go run ./main test-micro/main.go
runDelve:
	go run ./main test-delve/cmd/dlv/main.go
runCockroach:
	go run ./main tests/GoBench/Cockroach/27659/main.go
	go run ./main tests/GoBench/Cockroach/35501/main.go
runEtcd:
	go run ./main tests/GoBench/Etcd/4876/main.go
	go run ./main tests/GoBench/Etcd/8149/main.go
	go run ./main tests/GoBench/Etcd/9446/main.go
runGrpc:
	go run ./main tests/GoBench/Grpc/1748/main.go
	go run ./main tests/GoBench/Grpc/1862/main.go
	go run ./main tests/GoBench/Grpc/3090/main.go
runIstio:
	go run ./main tests/GoBench/Istio/8144/main.go
	go run ./main tests/GoBench/Istio/8214/main.go
	go run ./main tests/GoBench/Istio/8967/main.go
	go run ./main tests/GoBench/Istio/16742/main.go
runServing:
	go run ./main tests/GoBench/Serving/3148/main.go
runGoBench:
	go run ./main tests/GoBench/Cockroach/27659/main.go
	go run ./main tests/GoBench/Cockroach/35501/main.go
	go run ./main tests/GoBench/Etcd/4876/main.go
	go run ./main tests/GoBench/Etcd/8149/main.go
	go run ./main tests/GoBench/Etcd/9446/main.go
	go run ./main tests/GoBench/Grpc/1748/main.go
	go run ./main tests/GoBench/Grpc/1862/main.go
	go run ./main tests/GoBench/Grpc/3090/main.go
	go run ./main tests/GoBench/Istio/8144/main.go
	go run ./main tests/GoBench/Istio/8214/main.go
	go run ./main tests/GoBench/Istio/8967/main.go
	go run ./main tests/GoBench/Istio/16742/main.go
	go run ./main tests/GoBench/Kubernetes/79631/main.go
	go run ./main tests/GoBench/Kubernetes/80284/main.go
	go run ./main tests/GoBench/Kubernetes/81091/main.go
	go run ./main tests/GoBench/Kubernetes/81148/main.go
	go run ./main tests/GoBench/Kubernetes/88331/main.go
	go run ./main tests/GoBench/Serving/3148/main.go
runGodel2Race:
	go run ./main tests/godel2/ch-as-lock-race/main.go
	go run ./main tests/godel2/deposit-race/main.go
	go run ./main tests/godel2/prod-cons-race/main.go
	go run ./main tests/godel2/simple-race/main.go
	go run ./main tests/godel2/dine3-chan-race/main.go
	go run ./main tests/godel2/dine5-chan-race/main.go
runGodel2NoRace:
	go run ./main tests/godel2/ch-as-lock-fix/main.go
	go run ./main tests/godel2/deposit-fix/main.go
	go run ./main tests/godel2/prod-cons-fix/main.go
	go run ./main tests/godel2/simple-race-fix/main.go
	go run ./main tests/godel2/no-race/main.go
	go run ./main tests/godel2/dine3-chan-fix/main.go
	go run ./main tests/godel2/dine5-chan-fix/main.go
run:
	go run ./main tests/GoBench/Cockroach/27659/main.go
	go run ./main tests/GoBench/Cockroach/35501/main.go
	go run ./main tests/GoBench/Etcd/4876/main.go
	go run ./main tests/GoBench/Etcd/8149/main.go
	go run ./main tests/GoBench/Etcd/9446/main.go
	go run ./main tests/GoBench/Grpc/1748/main.go
	go run ./main tests/GoBench/Grpc/1862/main.go
	go run ./main tests/GoBench/Grpc/3090/main.go
	go run ./main tests/GoBench/Istio/8144/main.go
	go run ./main tests/GoBench/Istio/8214/main.go
	go run ./main tests/GoBench/Istio/8967/main.go
	go run ./main tests/GoBench/Istio/16742/main.go
	go run ./main tests/GoBench/Kubernetes/79631/main.go
	go run ./main tests/GoBench/Kubernetes/80284/main.go
	go run ./main tests/GoBench/Kubernetes/81091/main.go
	go run ./main tests/GoBench/Kubernetes/81148/main.go
	go run ./main tests/GoBench/Kubernetes/88331/main.go
	go run ./main tests/GoBench/Serving/3148/main.go
	go run ./main tests/godel2/ch-as-lock-race/main.go
	go run ./main tests/godel2/deposit-race/main.go
	go run ./main tests/godel2/prod-cons-race/main.go
	go run ./main tests/godel2/simple-race/main.go
	go run ./main tests/godel2/dine3-chan-race/main.go
	go run ./main tests/godel2/dine5-chan-race/main.go
