build:
	go build -o main main.go pointerAnalysis.go raceCollection.go sliceTools.go ssaInstructions.go staticAnalysis.go gorace.go printSource.go
runSelect:
	./main tests/select.go
runWaitgroup:
	./main tests/waitgroup.go
runKubed:
	./main tests/test-kubed/main.go
runNakama:
	./main tests/test-nakama/main.go
runHugo:
	./main tests/test-hugo/hugo-master/main.go
runTalisman:
	./main tests/test-talisman/talisman.go
runJsonnet:
	./main tests/test-jsonnet/cmd/jsonnet/cmd.go
runKsonnet:
	./main tests/test-ksonnet/cmd/ks/main.go
runGitea:
	./main tests/test-gitea/main.go
runFaas:
	./main tests/test-faas/gateway/main.go
runKit:
	./main tests/test-kit/cmd/kitgen/main.go
runMicro:
	./main tests/test-micro/main.go
runDelve:
	./main tests/test-delve/cmd/dlv/main.go
runK:
	./main tests/GoBench/Kubernetes/81091/main.go
runDeposite:
	./main tests/godel2/deposit-race/main.go
runProd:
	./main tests/godel2/prod-cons-race/main.go
runI:
	./main tests/GoBench/Istio/8214/main.go
runSelect2:
	./main tests/select_nonblock.go
runSelect3:
	./main tests/single_case_select.go
runG:
	./main -lockOps tests/grpc-go-master/examples/helloworld/greeter_client/main.go
runWait:
	./main tests/waitgroup.go
runCockroach:
	./main tests/GoBench/Cockroach/27659/main.go
	./main tests/GoBench/Cockroach/35501/main.go
runEtcd:
	./main tests/GoBench/Etcd/4876/main.go
	./main tests/GoBench/Etcd/8149/main.go
	./main tests/GoBench/Etcd/9446/main.go
runGrpc:
	./main tests/GoBench/Grpc/1748/main.go
	./main tests/GoBench/Grpc/1862/main.go
	./main tests/GoBench/Grpc/3090/main.go
runIstio:
	./main tests/GoBench/Istio/8144/main.go
	./main tests/GoBench/Istio/8214/main.go
	./main tests/GoBench/Istio/8967/main.go
	./main tests/GoBench/Istio/16742/main.go
runServing:
	./main tests/GoBench/Serving/3148/main.go
runGoBench:
	./main tests/GoBench/Cockroach/27659/main.go
	./main tests/GoBench/Cockroach/35501/main.go
	./main tests/GoBench/Etcd/4876/main.go
	./main tests/GoBench/Etcd/8149/main.go
	./main tests/GoBench/Etcd/9446/main.go
	./main tests/GoBench/Grpc/1748/main.go
	./main tests/GoBench/Grpc/1862/main.go
	./main tests/GoBench/Grpc/3090/main.go
	./main tests/GoBench/Istio/8144/main.go
	./main tests/GoBench/Istio/8214/main.go
	./main tests/GoBench/Istio/8967/main.go
	./main tests/GoBench/Istio/16742/main.go
	./main tests/GoBench/Kubernetes/79631/main.go
	./main tests/GoBench/Kubernetes/80284/main.go
	./main tests/GoBench/Kubernetes/81091/main.go
	./main tests/GoBench/Kubernetes/81148/main.go
	./main tests/GoBench/Kubernetes/88331/main.go
	./main tests/GoBench/Serving/3148/main.go
runGodel2Race:
	./main tests/godel2/ch-as-lock-race/main.go
	./main tests/godel2/deposit-race/main.go
	./main tests/godel2/prod-cons-race/main.go
	./main tests/godel2/simple-race/main.go
	./main tests/godel2/dine3-chan-race/main.go
	./main tests/godel2/dine5-chan-race/main.go
runGodel2NoRace:
	./main tests/godel2/ch-as-lock-fix/main.go
	./main tests/godel2/deposit-fix/main.go
	./main tests/godel2/prod-cons-fix/main.go
	./main tests/godel2/simple-race-fix/main.go
	./main tests/godel2/no-race/main.go
	./main tests/godel2/dine3-chan-fix/main.go
	./main tests/godel2/dine5-chan-fix/main.go
run:
	./main tests/GoBench/Cockroach/27659/main.go
	./main tests/GoBench/Cockroach/35501/main.go
	./main tests/GoBench/Etcd/4876/main.go
	./main tests/GoBench/Etcd/8149/main.go
	./main tests/GoBench/Etcd/9446/main.go
	./main tests/GoBench/Grpc/1748/main.go
	./main tests/GoBench/Grpc/1862/main.go
	./main tests/GoBench/Grpc/3090/main.go
	./main tests/GoBench/Istio/8144/main.go
	./main tests/GoBench/Istio/8214/main.go
	./main tests/GoBench/Istio/8967/main.go
	./main tests/GoBench/Istio/16742/main.go
	./main tests/GoBench/Kubernetes/79631/main.go
	./main tests/GoBench/Kubernetes/80284/main.go
	./main tests/GoBench/Kubernetes/81091/main.go
	./main tests/GoBench/Kubernetes/81148/main.go
	./main tests/GoBench/Kubernetes/88331/main.go
	./main tests/GoBench/Serving/3148/main.go
	./main tests/godel2/ch-as-lock-race/main.go
	./main tests/godel2/deposit-race/main.go
	./main tests/godel2/prod-cons-race/main.go
	./main tests/godel2/simple-race/main.go
	./main tests/godel2/dine3-chan-race/main.go
	./main tests/godel2/dine5-chan-race/main.go
